---
title: "Data_analysis_question3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Libraries:

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(multcompView)
theme_set(new=theme_bw())
```
##Importing data:

```{r}
data_exp1 <- as_tibble(read.csv(file="C:\\Documents\\ECOLE\\2021-2022 Montpellier SupAgro\\D4 JRL-AT\\Projects\\Experiments\\resultat_exp1.csv", header = TRUE, sep=",", dec= '.', stringsAsFactors=TRUE))

data_exp2 <- as_tibble(read.csv(file="C:\\Documents\\ECOLE\\2021-2022 Montpellier SupAgro\\D4 JRL-AT\\Projects\\Experiments\\resultat_exp2.csv", header = TRUE, sep=",", dec= '.', stringsAsFactors=TRUE))


data_exp3 <- as_tibble(read.csv(file="C:\\Documents\\ECOLE\\2021-2022 Montpellier SupAgro\\D4 JRL-AT\\Projects\\Experiments\\resultat_exp3.csv", header = TRUE, sep=",", dec= '.', stringsAsFactors=TRUE))


data_exp4 <- as_tibble(read.csv(file="C:\\Documents\\ECOLE\\2021-2022 Montpellier SupAgro\\D4 JRL-AT\\Projects\\Experiments\\resultat_exp4.csv", header = TRUE, sep=",", dec= '.', stringsAsFactors=TRUE))


data_exp5 <- as_tibble(read.csv(file="C:\\Documents\\ECOLE\\2021-2022 Montpellier SupAgro\\D4 JRL-AT\\Projects\\Experiments\\resultat_exp5.csv", header = TRUE, sep=",", dec= '.', stringsAsFactors=TRUE))


data_exp6 <- as_tibble(read.csv(file="C:\\Documents\\ECOLE\\2021-2022 Montpellier SupAgro\\D4 JRL-AT\\Projects\\Experiments\\resultat_exp6.csv", header = TRUE, sep=",", dec= '.', stringsAsFactors=TRUE))
```


#3. Is there a difference in infection according to the different soils considered ?

```{r}
ggplot(data_exp4, aes(Sol, Moyenne, fill=Sol))+
  geom_boxplot()+
  labs(title="Nombre de galles en fonction du sol de culture sans \ninoculation bactérienne")+
  theme(plot.title=element_text(face='bold'))
```

Nous allons maintenant voir si les résultats obtenus sont significativement différents ou non.

```{r}
test4<-lm(Moyenne~Sol, data=data_exp4)
anova(test4)
tukey4<-TukeyHSD(aov(test4))
multcompLetters(extract_p(test4$Sol))
```



